# Specify the Docker Compose file format version
version: '3.8'

# Define the services your application consists of
services:
  # The 'app' service is your custom application
  app:
    # Build the Dockerfile located in the current directory
    build: .
    # Map port 8080 on the host to port 80 in the container
    # This allows your application to be accessible on port 8080 of the host machine
    ports:
      - "8080:80"
    # Specify service dependencies. 'app' depends on 'redis' service being available before it starts
    depends_on:
      - redis
    # Environment variables passed to the 'app' service container
    environment:
      # Address for the Redis service, used by your application to connect to Redis
      REDIS_ADDR: redis:6379
    # Restart policy: Restart the service unless it was stopped manually
    restart: unless-stopped

  # The 'redis' service uses the official Redis image from Docker Hub
  redis:
    image: redis:alpine
    # Mount a named volume to persist Redis data
    # The volume is mounted at /data inside the container, which is the default save location for Redis
    volumes:
      - redis-data:/data
    # Restart policy: Restart the service unless it was stopped manually
    restart: unless-stopped

# Define volumes used by the services
volumes:
  # 'redis-data' volume used for persisting data generated by the Redis service
  redis-data:
